/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HospitalMedicalInventryWorkArea;

import Hospital.Employee;
import UI.MainFrame;
import Warehouse.MedicalSupplyInventory;
import Warehouse.Warehouse;
import Warehouse.WarehouseOrder;
import Warehouse.WarehouseOrderList;
import java.util.ArrayList;
import java.util.Random;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shreyas
 */
public class MedicalSuppliesOrder extends javax.swing.JPanel {

    /**
     * Creates new form MedicalSuppliesOrder
     */
    Warehouse warehouse;
    Employee employee;
    public MedicalSuppliesOrder(Warehouse warehouse, Employee employee) {
        initComponents();
        this.warehouse = warehouse;
        this.employee = employee;
        populateMedicalSupplies();
        
    }
    
    public void populateMedicalSupplies() {
        cmbequipName.removeAllItems();
        for(MedicalSupplyInventory medicalSupplyInventory : warehouse.getMedicalSupplyInventoryDirectory().getMedicalSupplyInventoryList()) {
            cmbequipName.addItem(medicalSupplyInventory.getEquipName());
           
        }
         cmbequipName.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPatientID = new javax.swing.JLabel();
        jLabelTitle2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCart = new javax.swing.JTable();
        jButtonPlaceOrder = new javax.swing.JButton();
        jButtonAddToCart = new javax.swing.JButton();
        jLabelPatientID1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        cmbequipName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtquant = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPatientID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPatientID.setText("Medical Equipment Name");
        jPanel1.add(jLabelPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 30));

        jLabelTitle2.setFont(new java.awt.Font("Times New Roman", 1, 56)); // NOI18N
        jLabelTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle2.setText("Hospital Test Database");
        jPanel1.add(jLabelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 706, -1));

        jTableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medical Equipment Name", "Medical Equipment Price", "Medical Equipment Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCart);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 820, 110));

        jButtonPlaceOrder.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPlaceOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButtonPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlaceOrder.setText("PLACE ORDER");
        jButtonPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlaceOrderActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, -1, -1));

        jButtonAddToCart.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAddToCart.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButtonAddToCart.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddToCart.setText("ADD TO CART");
        jButtonAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddToCartActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jLabelPatientID1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPatientID1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPatientID1.setText("Total");
        jPanel1.add(jLabelPatientID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 480, 270, 30));

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 220, 30));

        cmbequipName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbequipName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 150, 40));

        jLabel1.setText("Quantity:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        txtquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantActionPerformed(evt);
            }
        });
        jPanel1.add(txtquant, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 130, 40));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 880, 690));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 760));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlaceOrderActionPerformed
        
        if(txtTotal.getText().isBlank() || Double.valueOf(txtTotal.getText()) == 0.0){
            JOptionPane.showMessageDialog(this, "Please add order to cart");
            return;
        }
         DefaultTableModel modelCart = (DefaultTableModel) jTableCart.getModel();
        Random random = new Random();
        WarehouseOrderList warehouseOrderList = new WarehouseOrderList();
        warehouseOrderList.setId(String.valueOf(random.nextInt(1000)));
        ArrayList<WarehouseOrder> warehouseOrderArray = new ArrayList<>();
        String totalSum = txtTotal.getText();
        
        for (int i = 0; i < modelCart.getRowCount(); i++) {
        
            String equipName = modelCart.getValueAt(i, 0).toString();
            String quantity = modelCart.getValueAt(i, 1).toString();
            String price = modelCart.getValueAt(i, 2).toString();
            String orderAmount = String.valueOf(Double.parseDouble(price) * Double.parseDouble(quantity));
            int random2 = random.nextInt(1000);

            WarehouseOrder warehouseOrder = new WarehouseOrder(String.valueOf(random2), equipName ,orderAmount, quantity, false);
            warehouseOrderArray.add(warehouseOrder);
        
        }
        warehouseOrderList.setTotalAmount(totalSum);
        warehouseOrderList.setWarehouseOrderList(warehouseOrderArray);
        warehouse.addWarehouseOrder(warehouseOrderList);
        JOptionPane.showMessageDialog(this, "Your order has been placed");
        WarehouseAdminLandingPage walp = new WarehouseAdminLandingPage(warehouse, employee);
        MainFrame.mfInstance.setMainframeSplitFrame(walp);
    }//GEN-LAST:event_jButtonPlaceOrderActionPerformed

    private void jButtonAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddToCartActionPerformed
        // TODO add your handling code here:
        
        if(!txtquant.getText().isEmpty()&& txtquant.getText().matches("\\d+(\\.\\d+)?")){
            String equipName = (String) cmbequipName.getSelectedItem();
            String quantity = txtquant.getText();
            MedicalSupplyInventory selectMedicalSupplyInventory = null;
            for(MedicalSupplyInventory medicalSupplyInventory : warehouse.getMedicalSupplyInventoryDirectory().getMedicalSupplyInventoryList()) {
                if(equipName.equals(medicalSupplyInventory.getEquipName())) {
                    selectMedicalSupplyInventory = medicalSupplyInventory;
                    break;
                }               
            }
        DefaultTableModel modelCart = (DefaultTableModel) jTableCart.getModel();
        Object[] row = new Object[3];
        row[0] = selectMedicalSupplyInventory;
        row[1] = quantity;
        row[2] = selectMedicalSupplyInventory.getPrice();
        modelCart.addRow(row);
        updateTotalPrice();
        
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter a valid quantity");
        }
        txtquant.setText("");

    }//GEN-LAST:event_jButtonAddToCartActionPerformed
    
    private void updateTotalPrice() {
        DefaultTableModel model = (DefaultTableModel) jTableCart.getModel();
        int rowCount = model.getRowCount();
        double totalPrice = 0.0;

        for (int i = 0; i < rowCount; i++) {
            Object priceObject = model.getValueAt(i, 1);
            Object quantityObject = model.getValueAt(i, 2);
            if (priceObject != null) {
                double price = Double.parseDouble(priceObject.toString()) * Double.parseDouble(quantityObject.toString());
                totalPrice += price;
            }
        }
        txtTotal.setText(String.valueOf(totalPrice));
    }
    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           WarehouseAdminLandingPage walp = new WarehouseAdminLandingPage(warehouse, employee);
           MainFrame.mfInstance.setMainframeSplitFrame(walp);            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbequipName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddToCart;
    private javax.swing.JButton jButtonPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPatientID;
    private javax.swing.JLabel jLabelPatientID1;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCart;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtquant;
    // End of variables declaration//GEN-END:variables
}
