/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DoctorLogin;

import Hospital.Employee;
import Hospital.Hospital;
import Hospital.Patient;
import Hospital.PatientAppointment;
import UI.MainFrame;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author shrey
 */
public class AddNotes extends javax.swing.JPanel {

    /**
     * Creates new form LabTestReport
     */
    Hospital hospital;
    Employee doctor;
    Patient patient;
    public AddNotes(Hospital hospital, Employee doctor, Patient patient) {
        initComponents();
        this.hospital = hospital;
        this.doctor = doctor;
        this.patient = patient;
        txtPatName.setText(patient.getPatientName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPatName = new javax.swing.JTextField();
        txtPatName1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Appointment Notes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 14, 223, 45));

        txtPatName.setEditable(false);
        add(txtPatName, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 77, 107, -1));
        add(txtPatName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 132, 315, 84));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 253, 110, 30));

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setText("< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txtPatName1.getText().isBlank()){
                JOptionPane.showMessageDialog(this, "Please add notes");
                return;
            }
        for (PatientAppointment patientAppointment :doctor.getPatientAppointmentList()){
            
            if(patientAppointment.getPatient().getPatientName() == patient.getPatientName() && patientAppointment.getDesc().isBlank()) {
                
                patientAppointment.setDesc(txtPatName1.getText());
                JOptionPane.showMessageDialog(this, "Details added");
                ViewAppointmentJPanel vajp1 = new ViewAppointmentJPanel(hospital, doctor);
                MainFrame.mfInstance.setMainframeSplitFrame(vajp1);
            }
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  DoctorLandingPage vajp1 = new DoctorLandingPage(hospital, doctor);
           MainFrame.mfInstance.setMainframeSplitFrame(vajp1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPatName;
    private javax.swing.JTextField txtPatName1;
    // End of variables declaration//GEN-END:variables
}
