/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DoctorLogin;

import Hospital.Employee;
import Hospital.Hospital;
import Hospital.Patient;
import Hospital.PatientAppointment;
import Hospital.PatientTest;
import UI.MainFrame;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrey
 */
public class PatientDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewAppointmentHistory
     */
    Hospital hospital;
    Employee doctor;
    Patient patient;
    public PatientDetails(Hospital hospital, Employee doctor, Patient patient) {
        this.hospital = hospital;
        this.doctor = doctor;
        this.patient = patient;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppHis = new javax.swing.JTable();
        txtPatientName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbtLabTest = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("Patient Details");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 170, 30));

        tblAppHis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Appointment Notes"
            }
        ));
        jScrollPane1.setViewportView(tblAppHis);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 650, 210));

        txtPatientName.setEditable(false);
        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 120, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Lab Results");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 150, 40));

        tbtLabTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Test Name", "Results"
            }
        ));
        jScrollPane2.setViewportView(tbtLabTest);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 640, 160));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("< Back");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            DoctorLandingPage vajp1 = new DoctorLandingPage(hospital, doctor);
           MainFrame.mfInstance.setMainframeSplitFrame(vajp1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblAppHis;
    private javax.swing.JTable tbtLabTest;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        txtPatientName.setText(patient.getPatientName());
        
        DefaultTableModel model = (DefaultTableModel) tblAppHis.getModel();
        model.setRowCount(0);
        
        DefaultTableModel model1 = (DefaultTableModel) tbtLabTest.getModel();
        model1.setRowCount(0);
        
        try {
            for (PatientAppointment patientAppointment : hospital.getPatientAppointmentDirectory().getPatientAppointmentList()){
                if(patientAppointment.getPatient().getPatientName().equals(patient.getPatientName()) && !patientAppointment.getDesc().isBlank()) {
                    SimpleDateFormat df = new SimpleDateFormat("MM/dd/yyyy");
                    Date date = df.parse(patientAppointment.getAppointmentDate());
                    Date currentDate = new Date(System.currentTimeMillis());
                    if(date.before(currentDate)) {
                        Object[] row = new Object[2];
                        row[0] = patientAppointment.getAppointmentDate();
                        row[1] = patientAppointment.getDesc();
                        model.addRow(row);
                    }                    
                }

            }
            for (PatientTest patientTest : hospital.getPatientTestDirectory().getPatientTestList()){
                if(patientTest.getPatient().getPatientName().equals(patient.getPatientName()) && !patientTest.getDescr().isBlank()) {
                        Object[] row = new Object[3];
                        row[0] = patientTest.getTestDate();
                        row[1] = patientTest.getLabTest().getTestName();
                        row[2] = patientTest.getDescr();
                        model1.addRow(row);

                    }

            }            
        } catch(ParseException parseException) {
            
        }
        

        
    }
    
}
