/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DoctorLogin;

import Hospital.Employee;
import Hospital.Hospital;
import Hospital.Patient;
import Hospital.PatientAppointment;
import UI.MainFrame;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DateFormatter;

/**
 *
 * @author shrey
 */
public class ViewAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAppointmentJPanel
     */
    Hospital hospital;
    Employee doctor;
    public ViewAppointmentJPanel(Hospital hospital, Employee doctor) {
        initComponents();
        this.hospital = hospital;
        this.doctor = doctor;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 204, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("         View Appointment");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 260, 43));

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Time"
            }
        ));
        jScrollPane1.setViewportView(tblAppointments);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 275));

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setText("View Patient Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 40));

        jLabel1.setText("Date");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, 30));

        lblDate.setEditable(false);
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 117, 29));

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setText("Add Notes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 130, 40));

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setText("< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/9.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(1485, 784));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 920, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblAppointments.getSelectedRow();
//        
        if (selectedRowIndex<0) { 
            JOptionPane.showMessageDialog(this, "Please select a row to be displayed.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblAppointments.getModel();
      
        Patient patient = (Patient) model.getValueAt(selectedRowIndex, 0);
        PatientDetails pdjp = new PatientDetails(hospital, doctor, patient);
        MainFrame.mfInstance.setMainframeSplitFrame(pdjp);
        
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblAppointments.getSelectedRow();
//      
        if (selectedRowIndex < 0) { 
            JOptionPane.showMessageDialog(this, "Please select a row to add Notes.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblAppointments.getModel();
      
        Patient patient = (Patient) model.getValueAt(selectedRowIndex, 0);
        AddNotes pdjp = new AddNotes(hospital, doctor, patient);
        MainFrame.mfInstance.setMainframeSplitFrame(pdjp);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            DoctorLandingPage vajp1 = new DoctorLandingPage(hospital, doctor);
           MainFrame.mfInstance.setMainframeSplitFrame(vajp1); 
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lblDate;
    private javax.swing.JTable tblAppointments;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblAppointments.getModel();
        model.setRowCount(0);
        
        try {
            Format formatter = new SimpleDateFormat("MM/dd/yyyy");
            String todayDate = formatter.format(new Date(System.currentTimeMillis()));
            lblDate.setText(todayDate);  
            
            for (PatientAppointment patientAppointment :doctor.getPatientAppointmentList()){
                SimpleDateFormat df = new SimpleDateFormat("MM/dd/yyyy");
                Date date = df.parse(patientAppointment.getAppointmentDate());
                LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                if(localDate.equals(LocalDate.now()) && patientAppointment.getDesc().isBlank()) {
                    Object[] row = new Object[2];
                    row[0] = patientAppointment.getPatient();
                   
                    row[1] = patientAppointment.getAppointmentTime();
                    model.addRow(row);
                }
            }
        } catch(ParseException parseException) {
            
        }
        

        
    }
}
