/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Technician;

import Hospital.Employee;
import Hospital.Hospital;
import Hospital.PatientTest;
import UI.MainFrame;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrey
 */
public class OngoingOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OngoingOrdersJPanel
     */
    Hospital hospital;
    Employee employee;
    public OngoingOrdersJPanel(Hospital hospital, Employee employee) {
        initComponents();
        this.hospital = hospital;
        this.employee = employee;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtenterResults = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("Ongoing Orders");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 180, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "PatientID", "Test"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 590, 140));
        add(txtenterResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 220, 60));

        jLabel1.setText("Enter Results :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 170, 50));

        jButton2.setBackground(new java.awt.Color(0, 204, 255));
        jButton2.setText("< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 530));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selecedRowIndex = jTable1.getSelectedRow();
        if (selecedRowIndex<0) { 
            JOptionPane.showMessageDialog(this, "Please select a test");
            return;
        }
        
        if(txtenterResults.getText().isBlank()){
            JOptionPane.showMessageDialog(this,"Please enter the result");
            return;
        }
        
        PatientTest patientTest = (PatientTest) jTable1.getValueAt(selecedRowIndex, 0);
        patientTest.setDescr(txtenterResults.getText());
        JOptionPane.showMessageDialog(this,"Result added");
        Technician ocjp = new Technician(hospital, employee);
        MainFrame.mfInstance.setMainframeSplitFrame(ocjp);
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 Technician ocjp = new Technician(hospital, employee);
        MainFrame.mfInstance.setMainframeSplitFrame(ocjp);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtenterResults;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        List<PatientTest> patientTestList = hospital.getPatientTestDirectory().getPatientTestList().stream().filter(d -> d.getDescr().isBlank()).collect(Collectors.toList());
        for(PatientTest patientTest : patientTestList) {
            Object[] row = new Object[3];
            row[0] = patientTest;
            row[1] = patientTest.getPatient().getPatientId();
            row[2] = patientTest.getLabTest().getTestName();
            model.addRow(row);
        }
    }
}
