/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Hospital.Employee;
import Hospital.Hospital;
import Hospital.Role;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author shrey
 */
public class SignUp extends javax.swing.JPanel {

    /**
     * Creates new form SignUp
     */
    Hospital hospital;
    MainFrame mainFrame;
   
    public SignUp(Hospital hospital, MainFrame mainFrame) {
        initComponents();
        this.hospital = hospital;
        this.mainFrame = mainFrame;
        
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfirstName = new javax.swing.JTextField();
        txtlastName = new javax.swing.JTextField();
        cmbrole = new javax.swing.JComboBox<>();
        txtpassword = new javax.swing.JPasswordField();
        txtconPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("Sign Up");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel1.setText("First Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel2.setText("Last Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel3.setText("Role :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel4.setText("Password :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel5.setText("Confirn Password :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));
        add(txtfirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 240, 30));
        add(txtlastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 240, 30));

        cmbrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 240, 30));
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 240, 30));

        txtconPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconPassActionPerformed(evt);
            }
        });
        add(txtconPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 240, 30));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 423, 100, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/10.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -40, 800, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                                          
    
    String firstName = txtfirstName.getText().trim();
    String lastName = txtlastName.getText().trim();
    String role = cmbrole.getSelectedItem().toString();
    String password = new String(txtpassword.getPassword());
    String confirmPassword = new String(txtconPass.getPassword());

    
    if (firstName.isEmpty() || lastName.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required. Please fill in all the fields.");
        return;
    }

    
    if (!password.matches("^(?=.*[A-Z])(?=.*[!@#$%^&*(),.?\":{}|<>]).*$")) {
        JOptionPane.showMessageDialog(this, "Password should contain at least one capital letter and one special character.");
        return;
    }

    
    if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match. Please re-enter your password.");
        return;
    }
    Random random = new Random();
    int random1 = random.nextInt(1000);
    Employee e1 = null;
    if(role.equals("Doctor")) {
        e1 = new Employee(firstName, lastName, random1, 30000, hospital.getDepartmentDirectory().getDepartmentList().get(0), role, password);        
    }
    else {
        e1 = new Employee(firstName, lastName, random1, 30000, null, role, password);
    }
    
    hospital.addNewEmployee(e1);

    
    JOptionPane.showMessageDialog(this, "Account created successfully!");
    mainFrame.switchToLoginPage();
    
    
    


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtconPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbrole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField txtconPass;
    private javax.swing.JTextField txtfirstName;
    private javax.swing.JTextField txtlastName;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables

    private void populateComboBox() {
        
        cmbrole.removeAllItems();
        
       

        cmbrole.addItem("Doctor");
        cmbrole.addItem("Technician");
        cmbrole.addItem("Receptionist");
            
        
        cmbrole.setSelectedIndex(0);
    }
    
}
